import json

# Claude's results for each of the first 200 samples (by line number, 1-indexed)
# "correct" means I agree with the existing type
# Otherwise, the value is the corrected type I propose
claude_results = {
    1: "Conceptual Understanding",
    2: "Conceptual Understanding",
    3: "Methematical Derivation",
    4: "Methematical Derivation",
    5: "Performance Analysis",
    6: "correct",
    7: "Conceptual Understanding",
    8: "Conceptual Understanding",
    9: "correct",
    10: "correct",
    11: "correct",
    12: "correct",
    13: "Methematical Derivation",
    14: "correct",
    15: "correct",
    16: "Conceptual Understanding",
    17: "correct",
    18: "Conceptual Understanding",
    19: "Performance Analysis",
    20: "Methematical Derivation",
    21: "Design Implementation",
    22: "Methematical Derivation",
    23: "Methematical Derivation",
    24: "correct",
    25: "Design Implementation",
    26: "Application & Limitations",
    27: "Design Implementation",
    28: "correct",
    29: "Design Implementation",
    30: "correct",
    31: "Design Implementation",
    32: "correct",
    33: "Design Implementation",
    34: "Performance Analysis",
    35: "correct",
    36: "correct",
    37: "Performance Analysis",
    38: "Design Implementation",
    39: "Application & Limitations",
    40: "Application & Limitations",
    41: "Design Implementation",
    42: "Methematical Derivation",
    43: "correct",
    44: "Application & Limitations",
    45: "Design Implementation",
    46: "Conceptual Understanding",
    47: "correct",
    48: "Performance Analysis",
    49: "correct",
    50: "correct",
    51: "Conceptual Understanding",
    52: "Application & Limitations",
    53: "correct",
    54: "correct",
    55: "correct",
    56: "Performance Analysis",
    57: "correct",
    58: "Performance Analysis",
    59: "correct",
    60: "correct",
    61: "Methematical Derivation",
    62: "Application & Limitations",
    63: "correct",
    64: "correct",
    65: "Conceptual Understanding",
    66: "Conceptual Understanding",
    67: "Performance Analysis",
    68: "Methematical Derivation",
    69: "Design Implementation",
    70: "Methematical Derivation",
    71: "Methematical Derivation",
    72: "Conceptual Understanding",
    73: "Design Implementation",
    74: "correct",
    75: "correct",
    76: "Conceptual Understanding",
    77: "correct",
    78: "correct",
    79: "Conceptual Understanding",
    80: "Methematical Derivation",
    81: "correct",
    82: "correct",
    83: "Performance Analysis",
    84: "correct",
    85: "Performance Analysis",
    86: "correct",
    87: "Application & Limitations",
    88: "correct",
    89: "correct",
    90: "correct",
    91: "correct",
    92: "Application & Limitations",
    93: "correct",
    94: "Performance Analysis",
    95: "Application & Limitations",
    96: "Design Implementation",
    97: "correct",
    98: "correct",
    99: "Application & Limitations",
    100: "Design Implementation",
    101: "correct",
    102: "correct",
    103: "correct",
    104: "Performance Analysis",
    105: "correct",
    106: "Methematical Derivation",
    107: "correct",
    108: "correct",
    109: "Methematical Derivation",
    110: "Performance Analysis",
    111: "Design Implementation",
    112: "Conceptual Understanding",
    113: "Application & Limitations",
    114: "correct",
    115: "Design Implementation",
    116: "correct",
    117: "correct",
    118: "Performance Analysis",
    119: "Performance Analysis",
    120: "Methematical Derivation",
    121: "Conceptual Understanding",
    122: "correct",
    123: "Design Implementation",
    124: "correct",
    125: "Conceptual Understanding",
    126: "correct",
    127: "Design Implementation",
    128: "Conceptual Understanding",
    129: "Conceptual Understanding",
    130: "Design Implementation",
    131: "Conceptual Understanding",
    132: "correct",
    133: "correct",
    134: "correct",
    135: "correct",
    136: "correct",
    137: "correct",
    138: "Application & Limitations",
    139: "Performance Analysis",
    140: "Conceptual Understanding",
    141: "correct",
    142: "Conceptual Understanding",
    143: "correct",
    144: "correct",
    145: "Conceptual Understanding",
    146: "correct",
    147: "Application & Limitations",
    148: "correct",
    149: "Performance Analysis",
    150: "correct",
    151: "correct",
    152: "Design Implementation",
    153: "correct",
    154: "Conceptual Understanding",
    155: "Performance Analysis",
    156: "correct",
    157: "correct",
    158: "correct",
    159: "correct",
    160: "Conceptual Understanding",
    161: "correct",
    162: "correct",
    163: "correct",
    164: "correct",
    165: "correct",
    166: "correct",
    167: "correct",
    168: "Conceptual Understanding",
    169: "correct",
    170: "correct",
    171: "correct",
    172: "correct",
    173: "correct",
    174: "correct",
    175: "correct",
    176: "correct",
    177: "Methematical Derivation",
    178: "correct",
    179: "correct",
    180: "correct",
    181: "correct",
    182: "correct",
    183: "Conceptual Understanding",
    184: "Performance Analysis",
    185: "correct",
    186: "Conceptual Understanding",
    187: "correct",
    188: "correct",
    189: "correct",
    190: "correct",
    191: "correct",
    192: "Methematical Derivation",
    193: "correct",
    194: "correct",
    195: "correct",
    196: "correct",
    197: "correct",
    198: "correct",
    199: "correct",
    200: "Conceptual Understanding",
}

# Verify we have exactly 200 entries
assert len(claude_results) == 200, f"Expected 200 entries, got {len(claude_results)}"

input_path = "/home/xy67/RFIC Chatbot/QAs from textbooks/Claude_rating/testbench_type.jsonl"
output_path = "/home/xy67/RFIC Chatbot/QAs from textbooks/Claude_rating/testbench_type_Claude.jsonl"

correct_count = 0
incorrect_count = 0

with open(input_path, "r", encoding="utf-8") as fin, open(output_path, "w", encoding="utf-8") as fout:
    for i, line in enumerate(fin, start=1):
        if i > 200:
            break
        line = line.strip()
        if not line:
            continue
        obj = json.loads(line)
        result = claude_results[i]
        obj["Claude result"] = result
        if result == "correct":
            correct_count += 1
        else:
            incorrect_count += 1
        fout.write(json.dumps(obj, ensure_ascii=False) + "\n")

total = correct_count + incorrect_count
print(f"Total: {total}")
print(f"Correct: {correct_count}")
print(f"Incorrect: {incorrect_count}")
print(f"Correct ratio: {correct_count/total*100:.2f}%")
